//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string mssv { get; set; }
        public string hoten { get; set; }
        public string malop { get; set; }
    
        public virtual lop lop { get; set; }
    }
}
