//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryOnl
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public long id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public long categoryid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public string createdby { get; set; }
        public string modifiedby { get; set; }
        public byte[] images { get; set; }
    }
}
